name: finance_tracking
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  sqflite_sqlcipher: ^3.1.0+1
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.5
  dartz: ^0.10.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  syncfusion_flutter_charts: ^32.1.20
  table_calendar: ^3.2.0
  path: ^1.9.1
  lazy_load_scrollview: ^1.3.0
  pie_chart: ^5.4.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf